---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-02-service
  namespace: argocd
  finalizers:
   -  resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Olumide1996/My-Project.git
    targetRevision: HEAD
    path: ./kubernetes-manifest
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagation=foreground
      - PruneLast=true
