name: Build and push Image to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Build image
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.SAMPLE1_SA }}'

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=registry,ref=us-south1-docker.pkg.dev/cyber-457119/cyber-lab/cyber:latest
          cache-to: type=inline
          context: ./apps/computer_networks
          platforms: linux/amd64
          push: true
          tags: ${{ github.ref }}, "latest"
