name: Build and push Image to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Build image
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authorize Docker
        uses: docker/login-action@v3
        with:
          registry: us-south1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.SAMPLE2_SA }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            us-south1-docker.pkg.dev/cyber-457119/cyber-lab/cyber_2
          tags: |
            type=sha,prefix=
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=registry,ref=us-south1-docker.pkg.dev/cyber-457119/cyber-lab/cyber_2:latest
          cache-to: type=inline
          context: ./apps/computer_networks
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
