name: Sample 1 Service Account Creates a VM

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/comppute_vm_sample2.yaml"

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Create Conpute VM
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.SAMPLE1_SA }}'

# Simulate attacker creating vm
      - name: Create VM
        id: testim
        run: |
          gcloud compute instances create sample \
            --zone=us-central1-a \
            --machine-type=e2-medium \
            --image-family=debian-11 \
            --image-project=debian-cloud
